[CI] Stabilize flaky CI tests (#2931)
## Motivation for the change, related issues

Increases several timeouts and ensures the allocated resources are
disposed (via TypeScripts `using` keyword) to stabilize the following
flaky tests:

```
Run if [ "firefox" = "firefox" ]; then
  if [ "firefox" = "firefox" ]; then
    sudo -E HOME=/root XDG_RUNTIME_DIR=/root CI=true npx playwright test --config=packages/playground/website/playwright/playwright.ci.config.ts --project=firefox
  else
    sudo CI=true npx playwright test --config=packages/playground/website/playwright/playwright.ci.config.ts --project=firefox
  fi
  shell: /usr/bin/bash -e {0}
  env:
    NX_BASE: 5ce5752af3cde8b65c745c527c54f3b4bc164a00
    NX_HEAD: b07cdc84725654dc7fb85a544c89a68fd0a35cd4
Error: Process from config.webServer was not able to start. Exit code: 1

Error: Process completed with exit code 1.
```

```
   FAIL Test database > should install WordPress when SQL data path specified, even without SQLite ZIP path or SQLite driver directory 10064ms
       → Test timed out in 10000ms.

   FAIL  src/test/php-dynamic-loading.spec.ts > PHP 8.4 > XDebug > communicates with default DBGP port
   FAIL  src/test/php-networking.spec.ts > PHP 7.2 > cURL > should support multi handle requests
  Error: Test timed out in 5000ms.
```

```
  1) [firefox] › blueprints.spec.ts:526:5 › HTTPS requests via file_get_contents() to CORS-disabled URLs should succeed thanks to the CORS proxy 

    Error: Timed out 60000ms waiting for expect(locator).toContainText(expected)

    Locator: frameLocator('#playground-viewport:visible,.playground-viewport:visible').frameLocator('#wp').locator('body')
    - Expected string  - 1
    + Received string  + 5

    - int(340)
    +
    + Warning:  file_get_contents(https://playground.wordpress.net/test-fixtures/cors-file.html): Failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
    +  in /wordpress/https-test.php on line 4
    + int(0)
    +
    Call log:
      - expect.toContainText with timeout 60000ms
      - waiting for frameLocator('#playground-viewport:visible,.playground-viewport:visible').frameLocator('#wp').locator('body')
      -   locator resolved to <body>…</body>
      -   unexpected value "
    Warning:  file_get_contents(https://playground.wordpress.net/test-fixtures/cors-file.html): Failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
     in /wordpress/https-test.php on line 4
    int(0)
    "
      -   locator resolved to <body>…</body>
      -   unexpected value "
    Warning:  file_get_contents(https://playground.wordpress.net/test-fixtures/cors-file.html): Failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
     in /wordpress/https-test.php on line 4
    int(0)
    "
      -   locator resolved to <body>…</body>
      -   unexpected value "
    Warning:  file_get_contents(https://playground.wordpress.net/test-fixtures/cors-file.html): Failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
     in /wordpress/https-test.php on line 4
    int(0)
    "
      -   locator resolved to <body>…</body>
      -   unexpected value "
    Warning:  file_get_contents(https://playground.wordpress.net/test-fixtures/cors-file.html): Failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
     in /wordpress/https-test.php on line 4
    int(0)
    "
      -   locator resolved to <body>…</body>
      -   unexpected value "
    Warning:  file_get_contents(https://playground.wordpress.net/test-fixtures/cors-file.html): Failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
     in /wordpress/https-test.php on line 4
    int(0)
    "
      -   locator resolved to <body>…</body>
      -   unexpected value "
    Warning:  file_get_contents(https://playground.wordpress.net/test-fixtures/cors-file.html): Failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
     in /wordpress/https-test.php on line 4
    int(0)
    "
      -   locator resolved to <body>…</body>
      -   unexpected value "
    Warning:  file_get_contents(https://playground.wordpress.net/test-fixtures/cors-file.html): Failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
     in /wordpress/https-test.php on line 4
    int(0)
    "
      -   locator resolved to <body>…</body>
      -   unexpected value "
    Warning:  file_get_contents(https://playground.wordpress.net/test-fixtures/cors-file.html): Failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
     in /wordpress/https-test.php on line 4
    int(0)
    "
      -   locator resolved to <body>…</body>
      -   unexpected value "
    Warning:  file_get_contents(https://playground.wordpress.net/test-fixtures/cors-file.html): Failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request
     in /wordpress/https-test.php on line 4
    int(0)
    "
```