Update Lerna from 6.6.2 to 7.1.3 in order to run Release NPM packages Github Action (#3038)
## Motivation for the change, related issues

I noticed NPM packages were not updated since 4 weeks due to a `lerna
Err`:

```
lerna ERR! TypeError: resolvedPrettier.resolveConfig.sync is not a function
lerna ERR!     at maybeFormatFile (/home/runner/work/wordpress-playground/wordpress-playground/node_modules/lerna/dist/cli.js:5776:53)
lerna ERR!     at gitAdd (/home/runner/work/wordpress-playground/wordpress-playground/node_modules/lerna/dist/cli.js:5799:9)
lerna ERR!     at /home/runner/work/wordpress-playground/wordpress-playground/node_modules/lerna/dist/cli.js:6622:36
lerna ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
lerna ERR!     at async Promise.all (index 0)
```

I found [this issue](https://github.com/lerna/lerna/issues/3765) and
[this issue](https://github.com/lerna/lerna/issues/3775) on the `lerna`
github repository where it was mentionned that version `7.1.3` of lerna
fixed the above issue.

## Implementation details

Updating lerna version in github actions and in `package.json`

## Testing Instructions (or ideally a Blueprint)

CI - Release NPM packages - should pass.