[PHP] Fix external dynamic imports issue in PHP.wasm Web (#3093)
## Motivation for the change, related issues

Fixing follow-up issue
https://github.com/WordPress/wordpress-playground/pull/3085

I previously removed the Vite extension for External Dynamic Imports
thinking it was no longer necessary to fix the issue initiated by the
per-PHP-package split pull request. I was wrong. This pull request
re-creates the plugin but modifies the behavior to fix the current
issue.

The current issue returns this : 

```
Error: Error during dependency optimization:

✘ [ERROR] Could not resolve "./lib/extensions/intl/shared/icu.dat"

    node_modules/@php-wasm/web/index.js:2269:88:
      2269 │ ...wait import("./lib/extensions/intl/shared/icu.dat")).default,...
           ╵                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

## Implementation details

Re-create the `vite-external-dynamic-imports` file but :

```diff
    regex: /icu\.dat$/,
-    transform: (specifier) =>
-	`./${specifier.split('/').slice(-2).join('/')}`,
+    transform: (specifier) => `../../../${specifier}`,
},
```

## Testing Instructions (or ideally a Blueprint)

CI